// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShoutAPI.Database;

#nullable disable

namespace ShoutAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20230328001156_Added Registration table")]
    partial class AddedRegistrationtable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShoutAPI.Database.Models.Records+RegistrationData", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("clientId")
                        .HasColumnType("text");

                    b.Property<string>("dateRegistered")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("ShoutAPI.Database.Models.TestModel", b =>
                {
                    b.Property<long>("Key")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Key"));

                    b.Property<string>("DateAdded")
                        .HasColumnType("text");

                    b.Property<string>("EntryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RandomBool")
                        .HasColumnType("boolean");

                    b.HasKey("Key");

                    b.ToTable("TestData");
                });
#pragma warning restore 612, 618
        }
    }
}
